# Generated by Django 3.2 on 2023-07-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUsers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('pol', models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=10, null=True, verbose_name='Пол')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка пользователя')),
            ],
        ),
    ]
