# Generated by Django 3.2 on 2023-07-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUsers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('pol', models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужской', max_length=10, null=True, verbose_name='Пол')),
                ('image', models.BinaryField(blank=True, null=True, verbose_name='Аватарка пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='LikeUsers',
            fields=[
                ('id_user_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nameuser1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользователь который оценил')),
                ('id_user_2', models.IntegerField(blank=True, null=True, verbose_name='Айди пользователя которого оценили')),
                ('is_mutual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Оценили пользователя2')),
                ('image_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_dev.imageusers')),
            ],
        ),
    ]
