# Generated by Django 3.2 on 2023-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageusers',
            name='pol',
            field=models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужской', max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
